#! /bin/sh

# esy-build
#
# Wrapper to execute appropriate build strategy, based on platform

set -u
set -e

case "$(uname -s)" in
    CYGWIN*|MINGW32*|MSYS*)
        echo "[esy-build] Detected windows environment..."
        make -j$(nproc) world.opt
        make flexlink.opt
        ;;
    *)
        echo "[esy-build] Detected OSX / Linux environment"
        make -j$(nproc) world.opt
        ;;
esac

# Common build steps
exec make install
